//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Calculator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calculator.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CalculateExpression", ReplyAction="http://tempuri.org/ICalculator/CalculateExpressionResponse")]
        string CalculateExpression(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CalculateExpression", ReplyAction="http://tempuri.org/ICalculator/CalculateExpressionResponse")]
        System.Threading.Tasks.Task<string> CalculateExpressionAsync(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Set", ReplyAction="http://tempuri.org/ICalculator/SetResponse")]
        void Set(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Set", ReplyAction="http://tempuri.org/ICalculator/SetResponse")]
        System.Threading.Tasks.Task SetAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Add", ReplyAction="http://tempuri.org/ICalculator/AddResponse")]
        void Add(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Add", ReplyAction="http://tempuri.org/ICalculator/AddResponse")]
        System.Threading.Tasks.Task AddAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Substract", ReplyAction="http://tempuri.org/ICalculator/SubstractResponse")]
        void Substract(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Substract", ReplyAction="http://tempuri.org/ICalculator/SubstractResponse")]
        System.Threading.Tasks.Task SubstractAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiply", ReplyAction="http://tempuri.org/ICalculator/MultiplyResponse")]
        void Multiply(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiply", ReplyAction="http://tempuri.org/ICalculator/MultiplyResponse")]
        System.Threading.Tasks.Task MultiplyAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Divide", ReplyAction="http://tempuri.org/ICalculator/DivideResponse")]
        void Divide(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Divide", ReplyAction="http://tempuri.org/ICalculator/DivideResponse")]
        System.Threading.Tasks.Task DivideAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Result", ReplyAction="http://tempuri.org/ICalculator/ResultResponse")]
        double Result();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Result", ReplyAction="http://tempuri.org/ICalculator/ResultResponse")]
        System.Threading.Tasks.Task<double> ResultAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : ClientApp.Calculator.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<ClientApp.Calculator.ICalculator>, ClientApp.Calculator.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CalculateExpression(string expression) {
            return base.Channel.CalculateExpression(expression);
        }
        
        public System.Threading.Tasks.Task<string> CalculateExpressionAsync(string expression) {
            return base.Channel.CalculateExpressionAsync(expression);
        }
        
        public void Set(double a) {
            base.Channel.Set(a);
        }
        
        public System.Threading.Tasks.Task SetAsync(double a) {
            return base.Channel.SetAsync(a);
        }
        
        public void Add(double a) {
            base.Channel.Add(a);
        }
        
        public System.Threading.Tasks.Task AddAsync(double a) {
            return base.Channel.AddAsync(a);
        }
        
        public void Substract(double a) {
            base.Channel.Substract(a);
        }
        
        public System.Threading.Tasks.Task SubstractAsync(double a) {
            return base.Channel.SubstractAsync(a);
        }
        
        public void Multiply(double a) {
            base.Channel.Multiply(a);
        }
        
        public System.Threading.Tasks.Task MultiplyAsync(double a) {
            return base.Channel.MultiplyAsync(a);
        }
        
        public void Divide(double a) {
            base.Channel.Divide(a);
        }
        
        public System.Threading.Tasks.Task DivideAsync(double a) {
            return base.Channel.DivideAsync(a);
        }
        
        public double Result() {
            return base.Channel.Result();
        }
        
        public System.Threading.Tasks.Task<double> ResultAsync() {
            return base.Channel.ResultAsync();
        }
    }
}
